name: Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i -g pnpm
      - run: pnpm i vsce
      - run: pnpm vsce
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
